// Sample trivia questions for Blobby: Summit
// Organized by category with 200+ questions

export interface SampleQuestion {
  text: string;
  options: { text: string }[];
  correctOptionIndex: number;
  category: QuestionCategory;
  followUpText?: string; // Optional fun fact shown after reveal
  timeLimit?: number; // Default 30 if not specified
}

export type QuestionCategory =
  | "pop_culture"
  | "science"
  | "history"
  | "geography"
  | "sports"
  | "music"
  | "movies_tv"
  | "food_drink"
  | "technology"
  | "programming"
  | "animals"
  | "literature"
  | "general";

export const CATEGORY_LABELS: Record<QuestionCategory, string> = {
  pop_culture: "Pop Culture",
  science: "Science & Nature",
  history: "History",
  geography: "Geography",
  sports: "Sports",
  music: "Music",
  movies_tv: "Movies & TV",
  food_drink: "Food & Drink",
  technology: "Technology & Gadgets",
  programming: "Programming & Dev",
  animals: "Animals",
  literature: "Literature",
  general: "General Knowledge",
};

export const ALL_CATEGORIES: QuestionCategory[] = Object.keys(CATEGORY_LABELS) as QuestionCategory[];

export const sampleQuestions: SampleQuestion[] = [
  // ============================================
  // POP CULTURE (18 questions)
  // ============================================
  {
    text: "Which social media platform was originally called 'Picaboo'?",
    options: [
      { text: "Instagram" },
      { text: "Snapchat" },
      { text: "TikTok" },
      { text: "Pinterest" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    followUpText: "Snapchat launched in 2011 as Picaboo before rebranding later that year.",
    timeLimit: 15,
  },
  {
    text: "What year did the first iPhone launch?",
    options: [
      { text: "2005" },
      { text: "2007" },
      { text: "2009" },
      { text: "2011" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    followUpText: "Steve Jobs unveiled the iPhone on January 9, 2007, calling it a 'revolutionary product.'",
    timeLimit: 15,
  },
  {
    text: "Which streaming service produced 'Stranger Things'?",
    options: [
      { text: "Hulu" },
      { text: "Amazon Prime" },
      { text: "Netflix" },
      { text: "Disney+" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "What is the name of Elon Musk's space company?",
    options: [
      { text: "Blue Origin" },
      { text: "Virgin Galactic" },
      { text: "SpaceX" },
      { text: "Rocket Lab" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "Which artist's real name is Stefani Joanne Angelina Germanotta?",
    options: [
      { text: "Beyonce" },
      { text: "Lady Gaga" },
      { text: "Rihanna" },
      { text: "Katy Perry" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    timeLimit: 18,
  },
  {
    text: "What viral dance originated from the video game Fortnite?",
    options: [
      { text: "The Macarena" },
      { text: "The Floss" },
      { text: "The Shuffle" },
      { text: "The Robot" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "Which company owns Instagram?",
    options: [
      { text: "Google" },
      { text: "Microsoft" },
      { text: "Meta (Facebook)" },
      { text: "Twitter" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "What is the most-watched YouTube video of all time?",
    options: [
      { text: "Gangnam Style" },
      { text: "Baby Shark Dance" },
      { text: "Despacito" },
      { text: "See You Again" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    followUpText: "Baby Shark Dance has over 14 billion views!",
    timeLimit: 18,
  },
  {
    text: "Which reality TV show features Gordon Ramsay yelling at aspiring chefs?",
    options: [
      { text: "Top Chef" },
      { text: "Hell's Kitchen" },
      { text: "Chopped" },
      { text: "Iron Chef" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "What was the name of the viral dress that divided the internet over its color?",
    options: [
      { text: "The Red/Orange Dress" },
      { text: "The Blue/Gold Dress" },
      { text: "The Pink/Gray Dress" },
      { text: "The Green/Purple Dress" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    followUpText: "In 2015, 'The Dress' sparked a global debate - it was actually blue and black!",
    timeLimit: 18,
  },
  {
    text: "Which K-pop group performed at the 2022 FIFA World Cup opening ceremony?",
    options: [
      { text: "BLACKPINK" },
      { text: "BTS" },
      { text: "Jungkook" },
      { text: "EXO" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    timeLimit: 18,
  },
  {
    text: "What is the name of the fictional currency in Roblox?",
    options: [
      { text: "V-Bucks" },
      { text: "Robux" },
      { text: "Coins" },
      { text: "Gems" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "Which celebrity couple is known as 'Bennifer'?",
    options: [
      { text: "Brad Pitt & Jennifer Aniston" },
      { text: "Ben Affleck & Jennifer Lopez" },
      { text: "Ben Stiller & Jennifer Lopez" },
      { text: "Ben Affleck & Jennifer Garner" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    timeLimit: 18,
  },
  {
    text: "What was the best-selling video game console of all time?",
    options: [
      { text: "Xbox 360" },
      { text: "Nintendo Switch" },
      { text: "PlayStation 2" },
      { text: "Wii" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    followUpText: "The PS2 sold over 155 million units worldwide!",
    timeLimit: 18,
  },
  {
    text: "Which influencer is famous for saying 'It's everyday bro'?",
    options: [
      { text: "PewDiePie" },
      { text: "MrBeast" },
      { text: "Jake Paul" },
      { text: "Logan Paul" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "What app is known for its disappearing messages and filters?",
    options: [
      { text: "WhatsApp" },
      { text: "Snapchat" },
      { text: "Telegram" },
      { text: "Signal" },
    ],
    correctOptionIndex: 1,
    category: "pop_culture",
    timeLimit: 15,
  },
  {
    text: "Which podcast became the most downloaded on Spotify in 2020?",
    options: [
      { text: "Serial" },
      { text: "The Daily" },
      { text: "The Joe Rogan Experience" },
      { text: "Crime Junkie" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    timeLimit: 18,
  },
  {
    text: "What meme features a confused math lady?",
    options: [
      { text: "Distracted Boyfriend" },
      { text: "Woman Yelling at Cat" },
      { text: "Math Lady/Confused Lady" },
      { text: "Hide the Pain Harold" },
    ],
    correctOptionIndex: 2,
    category: "pop_culture",
    timeLimit: 18,
  },

  // ============================================
  // SCIENCE (20 questions)
  // ============================================
  {
    text: "What is the chemical symbol for gold?",
    options: [
      { text: "Go" },
      { text: "Gd" },
      { text: "Au" },
      { text: "Ag" },
    ],
    correctOptionIndex: 2,
    category: "science",
    followUpText: "Au comes from the Latin word 'aurum' meaning gold.",
    timeLimit: 15,
  },
  {
    text: "What planet is known as the 'Red Planet'?",
    options: [
      { text: "Venus" },
      { text: "Mars" },
      { text: "Jupiter" },
      { text: "Mercury" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "What is the hardest natural substance on Earth?",
    options: [
      { text: "Titanium" },
      { text: "Quartz" },
      { text: "Diamond" },
      { text: "Obsidian" },
    ],
    correctOptionIndex: 2,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "How many bones are in the adult human body?",
    options: [
      { text: "186" },
      { text: "206" },
      { text: "226" },
      { text: "256" },
    ],
    correctOptionIndex: 1,
    category: "science",
    followUpText: "Babies are born with about 270 bones, but many fuse together as we grow.",
    timeLimit: 18,
  },
  {
    text: "What is the largest organ in the human body?",
    options: [
      { text: "Liver" },
      { text: "Brain" },
      { text: "Skin" },
      { text: "Lungs" },
    ],
    correctOptionIndex: 2,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "What gas do plants absorb from the atmosphere?",
    options: [
      { text: "Oxygen" },
      { text: "Nitrogen" },
      { text: "Carbon Dioxide" },
      { text: "Hydrogen" },
    ],
    correctOptionIndex: 2,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "What is the speed of light in a vacuum (approximately)?",
    options: [
      { text: "300,000 km/s" },
      { text: "150,000 km/s" },
      { text: "500,000 km/s" },
      { text: "1,000,000 km/s" },
    ],
    correctOptionIndex: 0,
    category: "science",
    timeLimit: 18,
  },
  {
    text: "Which planet has the most moons in our solar system?",
    options: [
      { text: "Jupiter" },
      { text: "Saturn" },
      { text: "Uranus" },
      { text: "Neptune" },
    ],
    correctOptionIndex: 1,
    category: "science",
    followUpText: "Saturn has 146 confirmed moons as of 2023, beating Jupiter's 95!",
    timeLimit: 18,
  },
  {
    text: "What is the powerhouse of the cell?",
    options: [
      { text: "Nucleus" },
      { text: "Ribosome" },
      { text: "Mitochondria" },
      { text: "Golgi apparatus" },
    ],
    correctOptionIndex: 2,
    category: "science",
    followUpText: "This is perhaps the most famous biology fact meme of all time!",
    timeLimit: 15,
  },
  {
    text: "What is the most abundant gas in Earth's atmosphere?",
    options: [
      { text: "Oxygen" },
      { text: "Carbon Dioxide" },
      { text: "Nitrogen" },
      { text: "Argon" },
    ],
    correctOptionIndex: 2,
    category: "science",
    followUpText: "Nitrogen makes up about 78% of our atmosphere!",
    timeLimit: 15,
  },
  {
    text: "What type of animal is a Komodo dragon?",
    options: [
      { text: "Amphibian" },
      { text: "Reptile" },
      { text: "Mammal" },
      { text: "Bird" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "What is the chemical formula for water?",
    options: [
      { text: "CO2" },
      { text: "H2O" },
      { text: "NaCl" },
      { text: "O2" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 12,
  },
  {
    text: "How long does it take for light from the Sun to reach Earth?",
    options: [
      { text: "8 seconds" },
      { text: "8 minutes" },
      { text: "8 hours" },
      { text: "8 days" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 18,
  },
  {
    text: "What is the study of earthquakes called?",
    options: [
      { text: "Meteorology" },
      { text: "Seismology" },
      { text: "Geology" },
      { text: "Volcanology" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "What type of bond forms when atoms share electrons?",
    options: [
      { text: "Ionic bond" },
      { text: "Covalent bond" },
      { text: "Metallic bond" },
      { text: "Hydrogen bond" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 18,
  },
  {
    text: "What is the closest star to Earth (besides the Sun)?",
    options: [
      { text: "Alpha Centauri" },
      { text: "Proxima Centauri" },
      { text: "Sirius" },
      { text: "Betelgeuse" },
    ],
    correctOptionIndex: 1,
    category: "science",
    followUpText: "Proxima Centauri is about 4.24 light-years away from Earth.",
    timeLimit: 18,
  },
  {
    text: "What is absolute zero in Celsius?",
    options: [
      { text: "-100C" },
      { text: "-273C" },
      { text: "-373C" },
      { text: "0C" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 18,
  },
  {
    text: "What vitamin does the body produce when exposed to sunlight?",
    options: [
      { text: "Vitamin A" },
      { text: "Vitamin B" },
      { text: "Vitamin C" },
      { text: "Vitamin D" },
    ],
    correctOptionIndex: 3,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "What is the process by which plants make their own food?",
    options: [
      { text: "Respiration" },
      { text: "Photosynthesis" },
      { text: "Fermentation" },
      { text: "Digestion" },
    ],
    correctOptionIndex: 1,
    category: "science",
    timeLimit: 15,
  },
  {
    text: "Which blood type is known as the universal donor?",
    options: [
      { text: "A" },
      { text: "B" },
      { text: "AB" },
      { text: "O" },
    ],
    correctOptionIndex: 3,
    category: "science",
    timeLimit: 15,
  },

  // ============================================
  // HISTORY (18 questions)
  // ============================================
  {
    text: "In what year did World War II end?",
    options: [
      { text: "1943" },
      { text: "1944" },
      { text: "1945" },
      { text: "1946" },
    ],
    correctOptionIndex: 2,
    category: "history",
    timeLimit: 15,
  },
  {
    text: "Who was the first person to walk on the moon?",
    options: [
      { text: "Buzz Aldrin" },
      { text: "Neil Armstrong" },
      { text: "John Glenn" },
      { text: "Yuri Gagarin" },
    ],
    correctOptionIndex: 1,
    category: "history",
    followUpText: "Neil Armstrong took his famous first step on July 20, 1969.",
    timeLimit: 15,
  },
  {
    text: "Which ancient wonder was located in Alexandria, Egypt?",
    options: [
      { text: "Colossus of Rhodes" },
      { text: "Hanging Gardens" },
      { text: "Lighthouse of Alexandria" },
      { text: "Temple of Artemis" },
    ],
    correctOptionIndex: 2,
    category: "history",
    timeLimit: 18,
  },
  {
    text: "Who painted the Mona Lisa?",
    options: [
      { text: "Michelangelo" },
      { text: "Leonardo da Vinci" },
      { text: "Raphael" },
      { text: "Botticelli" },
    ],
    correctOptionIndex: 1,
    category: "history",
    timeLimit: 15,
  },
  {
    text: "Which empire was ruled by Genghis Khan?",
    options: [
      { text: "Ottoman Empire" },
      { text: "Roman Empire" },
      { text: "Mongol Empire" },
      { text: "Persian Empire" },
    ],
    correctOptionIndex: 2,
    category: "history",
    timeLimit: 16,
  },
  {
    text: "What year did the Berlin Wall fall?",
    options: [
      { text: "1987" },
      { text: "1989" },
      { text: "1991" },
      { text: "1993" },
    ],
    correctOptionIndex: 1,
    category: "history",
    followUpText: "The Berlin Wall fell on November 9, 1989, leading to German reunification.",
    timeLimit: 15,
  },
  {
    text: "Who was the first female Prime Minister of the United Kingdom?",
    options: [
      { text: "Theresa May" },
      { text: "Margaret Thatcher" },
      { text: "Queen Victoria" },
      { text: "Elizabeth II" },
    ],
    correctOptionIndex: 1,
    category: "history",
    timeLimit: 18,
  },
  {
    text: "What was the name of the ship the Pilgrims sailed to America?",
    options: [
      { text: "Santa Maria" },
      { text: "Mayflower" },
      { text: "Endeavour" },
      { text: "Victoria" },
    ],
    correctOptionIndex: 1,
    category: "history",
    timeLimit: 15,
  },
  {
    text: "In which city was the Titanic built?",
    options: [
      { text: "London" },
      { text: "Liverpool" },
      { text: "Belfast" },
      { text: "Southampton" },
    ],
    correctOptionIndex: 2,
    category: "history",
    followUpText: "The Titanic was built at the Harland and Wolff shipyard in Belfast, Northern Ireland.",
    timeLimit: 18,
  },
  {
    text: "Which French leader was exiled to the island of Elba?",
    options: [
      { text: "Louis XIV" },
      { text: "Napoleon Bonaparte" },
      { text: "Charles de Gaulle" },
      { text: "Charlemagne" },
    ],
    correctOptionIndex: 1,
    category: "history",
    timeLimit: 18,
  },
  {
    text: "What was the last dynasty of China?",
    options: [
      { text: "Ming Dynasty" },
      { text: "Tang Dynasty" },
      { text: "Qing Dynasty" },
      { text: "Han Dynasty" },
    ],
    correctOptionIndex: 2,
    category: "history",
    timeLimit: 18,
  },
  {
    text: "Who wrote the Declaration of Independence?",
    options: [
      { text: "George Washington" },
      { text: "Benjamin Franklin" },
      { text: "Thomas Jefferson" },
      { text: "John Adams" },
    ],
    correctOptionIndex: 2,
    category: "history",
    timeLimit: 15,
  },
  {
    text: "What ancient civilization built the Machu Picchu complex?",
    options: [
      { text: "Aztec" },
      { text: "Maya" },
      { text: "Inca" },
      { text: "Olmec" },
    ],
    correctOptionIndex: 2,
    category: "history",
    timeLimit: 15,
  },
  {
    text: "In what year did the American Civil War begin?",
    options: [
      { text: "1851" },
      { text: "1861" },
      { text: "1871" },
      { text: "1881" },
    ],
    correctOptionIndex: 1,
    category: "history",
    timeLimit: 18,
  },
  {
    text: "Who was the first Emperor of Rome?",
    options: [
      { text: "Julius Caesar" },
      { text: "Augustus" },
      { text: "Nero" },
      { text: "Caligula" },
    ],
    correctOptionIndex: 1,
    category: "history",
    followUpText: "Augustus (formerly Octavian) became the first Roman Emperor in 27 BC.",
    timeLimit: 18,
  },
  {
    text: "What event sparked World War I?",
    options: [
      { text: "Invasion of Poland" },
      { text: "Sinking of the Lusitania" },
      { text: "Assassination of Archduke Franz Ferdinand" },
      { text: "Treaty of Versailles" },
    ],
    correctOptionIndex: 2,
    category: "history",
    timeLimit: 20,
  },
  {
    text: "Which country gifted the Statue of Liberty to the United States?",
    options: [
      { text: "England" },
      { text: "France" },
      { text: "Germany" },
      { text: "Italy" },
    ],
    correctOptionIndex: 1,
    category: "history",
    timeLimit: 15,
  },
  {
    text: "What was the codename for the Allied invasion of Normandy in 1944?",
    options: [
      { text: "Operation Overlord" },
      { text: "Operation Barbarossa" },
      { text: "Operation Market Garden" },
      { text: "Operation Torch" },
    ],
    correctOptionIndex: 0,
    category: "history",
    timeLimit: 20,
  },

  // ============================================
  // GEOGRAPHY (18 questions)
  // ============================================
  {
    text: "What is the smallest country in the world by area?",
    options: [
      { text: "Monaco" },
      { text: "Liechtenstein" },
      { text: "Vatican City" },
      { text: "San Marino" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    timeLimit: 16,
  },
  {
    text: "What is the capital of Australia?",
    options: [
      { text: "Sydney" },
      { text: "Melbourne" },
      { text: "Canberra" },
      { text: "Brisbane" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    followUpText: "A common mistake! Sydney is the largest city, but Canberra is the capital.",
    timeLimit: 15,
  },
  {
    text: "Which country has the most natural lakes?",
    options: [
      { text: "United States" },
      { text: "Russia" },
      { text: "Canada" },
      { text: "Finland" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    followUpText: "Canada has over 60% of all natural lakes in the world!",
    timeLimit: 18,
  },
  {
    text: "What is the longest river in the world?",
    options: [
      { text: "Amazon" },
      { text: "Nile" },
      { text: "Yangtze" },
      { text: "Mississippi" },
    ],
    correctOptionIndex: 1,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "In which country would you find Machu Picchu?",
    options: [
      { text: "Chile" },
      { text: "Bolivia" },
      { text: "Peru" },
      { text: "Ecuador" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "What is the largest desert in the world?",
    options: [
      { text: "Sahara" },
      { text: "Arabian" },
      { text: "Gobi" },
      { text: "Antarctic" },
    ],
    correctOptionIndex: 3,
    category: "geography",
    followUpText: "Surprise! A desert is defined by low precipitation, not heat. Antarctica is technically the world's largest desert!",
    timeLimit: 18,
  },
  {
    text: "Which European city is divided by the Bosphorus strait?",
    options: [
      { text: "Athens" },
      { text: "Istanbul" },
      { text: "Venice" },
      { text: "Budapest" },
    ],
    correctOptionIndex: 1,
    category: "geography",
    timeLimit: 17,
  },
  {
    text: "What is the tallest mountain in the world?",
    options: [
      { text: "K2" },
      { text: "Mount Everest" },
      { text: "Kangchenjunga" },
      { text: "Lhotse" },
    ],
    correctOptionIndex: 1,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "Which country is home to the Great Barrier Reef?",
    options: [
      { text: "Indonesia" },
      { text: "Philippines" },
      { text: "Australia" },
      { text: "Thailand" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "What is the capital of Canada?",
    options: [
      { text: "Toronto" },
      { text: "Vancouver" },
      { text: "Ottawa" },
      { text: "Montreal" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "Which African country has the largest population?",
    options: [
      { text: "Egypt" },
      { text: "South Africa" },
      { text: "Nigeria" },
      { text: "Ethiopia" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    followUpText: "Nigeria has over 220 million people, making it the most populous country in Africa.",
    timeLimit: 18,
  },
  {
    text: "What ocean lies between Africa and Australia?",
    options: [
      { text: "Pacific Ocean" },
      { text: "Atlantic Ocean" },
      { text: "Indian Ocean" },
      { text: "Arctic Ocean" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "Which country is known as the Land of the Rising Sun?",
    options: [
      { text: "China" },
      { text: "Japan" },
      { text: "South Korea" },
      { text: "Vietnam" },
    ],
    correctOptionIndex: 1,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "What is the smallest US state by area?",
    options: [
      { text: "Delaware" },
      { text: "Connecticut" },
      { text: "Rhode Island" },
      { text: "Hawaii" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    timeLimit: 15,
  },
  {
    text: "Which country has the most time zones?",
    options: [
      { text: "Russia" },
      { text: "United States" },
      { text: "France" },
      { text: "China" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    followUpText: "France has 12 time zones due to its overseas territories! Russia has 11.",
    timeLimit: 18,
  },
  {
    text: "What is the deepest point in the ocean?",
    options: [
      { text: "Mariana Trench" },
      { text: "Puerto Rico Trench" },
      { text: "Java Trench" },
      { text: "Philippine Trench" },
    ],
    correctOptionIndex: 0,
    category: "geography",
    timeLimit: 18,
  },
  {
    text: "Which two countries share the longest international border?",
    options: [
      { text: "USA and Mexico" },
      { text: "Russia and China" },
      { text: "USA and Canada" },
      { text: "Brazil and Argentina" },
    ],
    correctOptionIndex: 2,
    category: "geography",
    followUpText: "The US-Canada border stretches 8,891 km (5,525 miles)!",
    timeLimit: 18,
  },
  {
    text: "What is the only country that borders both France and the United Kingdom?",
    options: [
      { text: "Belgium" },
      { text: "Spain" },
      { text: "Monaco" },
      { text: "None - trick question" },
    ],
    correctOptionIndex: 3,
    category: "geography",
    followUpText: "The UK is an island nation and doesn't share a land border with any European country.",
    timeLimit: 20,
  },

  // ============================================
  // SPORTS (17 questions)
  // ============================================
  {
    text: "How many players are on a standard soccer team on the field?",
    options: [
      { text: "9" },
      { text: "10" },
      { text: "11" },
      { text: "12" },
    ],
    correctOptionIndex: 2,
    category: "sports",
    timeLimit: 15,
  },
  {
    text: "Which country has won the most FIFA World Cup titles?",
    options: [
      { text: "Germany" },
      { text: "Argentina" },
      { text: "Brazil" },
      { text: "Italy" },
    ],
    correctOptionIndex: 2,
    category: "sports",
    followUpText: "Brazil has won 5 World Cups: 1958, 1962, 1970, 1994, and 2002.",
    timeLimit: 16,
  },
  {
    text: "What is the only sport to have been played on the moon?",
    options: [
      { text: "Frisbee" },
      { text: "Golf" },
      { text: "Baseball" },
      { text: "Tennis" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    followUpText: "Astronaut Alan Shepard hit two golf balls on the moon during Apollo 14 in 1971!",
    timeLimit: 18,
  },
  {
    text: "In which year were the first modern Olympic Games held?",
    options: [
      { text: "1876" },
      { text: "1896" },
      { text: "1900" },
      { text: "1912" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    timeLimit: 17,
  },
  {
    text: "How long is an Olympic swimming pool?",
    options: [
      { text: "25 meters" },
      { text: "50 meters" },
      { text: "75 meters" },
      { text: "100 meters" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    timeLimit: 15,
  },
  {
    text: "Which tennis tournament is played on grass?",
    options: [
      { text: "French Open" },
      { text: "US Open" },
      { text: "Australian Open" },
      { text: "Wimbledon" },
    ],
    correctOptionIndex: 3,
    category: "sports",
    timeLimit: 15,
  },
  {
    text: "How many points is a touchdown worth in American football?",
    options: [
      { text: "3" },
      { text: "6" },
      { text: "7" },
      { text: "8" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    timeLimit: 15,
  },
  {
    text: "Which country invented basketball?",
    options: [
      { text: "United States" },
      { text: "Canada" },
      { text: "England" },
      { text: "France" },
    ],
    correctOptionIndex: 0,
    category: "sports",
    followUpText: "Basketball was invented in 1891 by Canadian-American James Naismith in Massachusetts.",
    timeLimit: 18,
  },
  {
    text: "What is the highest possible score in a single frame of bowling?",
    options: [
      { text: "10" },
      { text: "20" },
      { text: "30" },
      { text: "50" },
    ],
    correctOptionIndex: 2,
    category: "sports",
    followUpText: "A strike followed by two more strikes gives you 30 points for that frame!",
    timeLimit: 18,
  },
  {
    text: "Which athlete has won the most Olympic gold medals?",
    options: [
      { text: "Usain Bolt" },
      { text: "Michael Phelps" },
      { text: "Carl Lewis" },
      { text: "Simone Biles" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    followUpText: "Michael Phelps has 23 Olympic gold medals, the most of any athlete in history!",
    timeLimit: 18,
  },
  {
    text: "In which sport would you perform a 'slam dunk'?",
    options: [
      { text: "Volleyball" },
      { text: "Basketball" },
      { text: "Tennis" },
      { text: "Handball" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    timeLimit: 12,
  },
  {
    text: "What is the diameter of a basketball hoop in inches?",
    options: [
      { text: "15 inches" },
      { text: "18 inches" },
      { text: "21 inches" },
      { text: "24 inches" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    timeLimit: 18,
  },
  {
    text: "Which NFL team has won the most Super Bowls?",
    options: [
      { text: "Dallas Cowboys" },
      { text: "New England Patriots" },
      { text: "Pittsburgh Steelers" },
      { text: "San Francisco 49ers" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    followUpText: "As of 2024, the Patriots are tied with the Steelers at 6 Super Bowl wins each!",
    timeLimit: 18,
  },
  {
    text: "What is the term for three strikes in a row in bowling?",
    options: [
      { text: "Triple" },
      { text: "Turkey" },
      { text: "Trio" },
      { text: "Trifecta" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    timeLimit: 15,
  },
  {
    text: "How many Grand Slam tennis tournaments are there per year?",
    options: [
      { text: "2" },
      { text: "3" },
      { text: "4" },
      { text: "5" },
    ],
    correctOptionIndex: 2,
    category: "sports",
    timeLimit: 15,
  },
  {
    text: "Which country hosted the 2016 Summer Olympics?",
    options: [
      { text: "China" },
      { text: "Brazil" },
      { text: "United Kingdom" },
      { text: "Russia" },
    ],
    correctOptionIndex: 1,
    category: "sports",
    timeLimit: 15,
  },
  {
    text: "What color is the center of an archery target?",
    options: [
      { text: "Red" },
      { text: "Blue" },
      { text: "Yellow (Gold)" },
      { text: "White" },
    ],
    correctOptionIndex: 2,
    category: "sports",
    timeLimit: 15,
  },

  // ============================================
  // MUSIC (17 questions)
  // ============================================
  {
    text: "Which band released the album 'Abbey Road'?",
    options: [
      { text: "The Rolling Stones" },
      { text: "Led Zeppelin" },
      { text: "The Beatles" },
      { text: "Pink Floyd" },
    ],
    correctOptionIndex: 2,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "Who is known as the 'King of Pop'?",
    options: [
      { text: "Elvis Presley" },
      { text: "Prince" },
      { text: "Michael Jackson" },
      { text: "Freddie Mercury" },
    ],
    correctOptionIndex: 2,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "What instrument does a pianist play?",
    options: [
      { text: "Guitar" },
      { text: "Drums" },
      { text: "Piano" },
      { text: "Violin" },
    ],
    correctOptionIndex: 2,
    category: "music",
    timeLimit: 10,
  },
  {
    text: "Which artist released the album 'Thriller'?",
    options: [
      { text: "Prince" },
      { text: "Michael Jackson" },
      { text: "Madonna" },
      { text: "Whitney Houston" },
    ],
    correctOptionIndex: 1,
    category: "music",
    followUpText: "Thriller is the best-selling album of all time with over 70 million copies sold!",
    timeLimit: 15,
  },
  {
    text: "What music streaming service is known for its green logo?",
    options: [
      { text: "Apple Music" },
      { text: "Tidal" },
      { text: "Spotify" },
      { text: "Pandora" },
    ],
    correctOptionIndex: 2,
    category: "music",
    timeLimit: 12,
  },
  {
    text: "Which rock band is Freddie Mercury famous for fronting?",
    options: [
      { text: "Led Zeppelin" },
      { text: "Queen" },
      { text: "The Who" },
      { text: "Aerosmith" },
    ],
    correctOptionIndex: 1,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "What is the highest female singing voice?",
    options: [
      { text: "Alto" },
      { text: "Mezzo-soprano" },
      { text: "Soprano" },
      { text: "Contralto" },
    ],
    correctOptionIndex: 2,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "Which pop star is known as 'The Material Girl'?",
    options: [
      { text: "Cher" },
      { text: "Madonna" },
      { text: "Cyndi Lauper" },
      { text: "Janet Jackson" },
    ],
    correctOptionIndex: 1,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "What year was the first Woodstock festival held?",
    options: [
      { text: "1965" },
      { text: "1967" },
      { text: "1969" },
      { text: "1971" },
    ],
    correctOptionIndex: 2,
    category: "music",
    followUpText: "Woodstock took place in August 1969 and attracted about 400,000 people!",
    timeLimit: 18,
  },
  {
    text: "Which Beatles member was assassinated in 1980?",
    options: [
      { text: "Paul McCartney" },
      { text: "George Harrison" },
      { text: "Ringo Starr" },
      { text: "John Lennon" },
    ],
    correctOptionIndex: 3,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "What genre of music originated in Jamaica?",
    options: [
      { text: "Salsa" },
      { text: "Reggae" },
      { text: "Bossa Nova" },
      { text: "Tango" },
    ],
    correctOptionIndex: 1,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "Which rapper created the album 'The Marshall Mathers LP'?",
    options: [
      { text: "Jay-Z" },
      { text: "Eminem" },
      { text: "Kanye West" },
      { text: "50 Cent" },
    ],
    correctOptionIndex: 1,
    category: "music",
    timeLimit: 18,
  },
  {
    text: "How many strings does a standard guitar have?",
    options: [
      { text: "4" },
      { text: "5" },
      { text: "6" },
      { text: "7" },
    ],
    correctOptionIndex: 2,
    category: "music",
    timeLimit: 12,
  },
  {
    text: "Which classical composer became deaf later in life?",
    options: [
      { text: "Mozart" },
      { text: "Bach" },
      { text: "Beethoven" },
      { text: "Chopin" },
    ],
    correctOptionIndex: 2,
    category: "music",
    followUpText: "Beethoven composed some of his greatest works, including his 9th Symphony, while completely deaf!",
    timeLimit: 18,
  },
  {
    text: "What is Taylor Swift's first album called?",
    options: [
      { text: "Fearless" },
      { text: "Taylor Swift" },
      { text: "Speak Now" },
      { text: "Red" },
    ],
    correctOptionIndex: 1,
    category: "music",
    timeLimit: 15,
  },
  {
    text: "Which country is K-pop from?",
    options: [
      { text: "Japan" },
      { text: "China" },
      { text: "South Korea" },
      { text: "Thailand" },
    ],
    correctOptionIndex: 2,
    category: "music",
    timeLimit: 12,
  },
  {
    text: "What instrument is Yo-Yo Ma famous for playing?",
    options: [
      { text: "Violin" },
      { text: "Cello" },
      { text: "Piano" },
      { text: "Flute" },
    ],
    correctOptionIndex: 1,
    category: "music",
    timeLimit: 18,
  },

  // ============================================
  // MOVIES & TV (18 questions)
  // ============================================
  {
    text: "What TV show features a chemistry teacher turned drug kingpin?",
    options: [
      { text: "The Wire" },
      { text: "Breaking Bad" },
      { text: "Ozark" },
      { text: "Narcos" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "What is the highest-grossing film of all time (not adjusted for inflation)?",
    options: [
      { text: "Avengers: Endgame" },
      { text: "Avatar" },
      { text: "Titanic" },
      { text: "Star Wars: The Force Awakens" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 18,
  },
  {
    text: "Which actress has won the most Academy Awards?",
    options: [
      { text: "Meryl Streep" },
      { text: "Katharine Hepburn" },
      { text: "Cate Blanchett" },
      { text: "Frances McDormand" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    followUpText: "Katharine Hepburn won 4 Oscars for Best Actress over her career!",
    timeLimit: 18,
  },
  {
    text: "What is the name of the coffee shop in 'Friends'?",
    options: [
      { text: "The Coffee Bean" },
      { text: "Central Perk" },
      { text: "Mocha Joe's" },
      { text: "The Brew House" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "Which director won an Oscar for 'Oppenheimer'?",
    options: [
      { text: "Steven Spielberg" },
      { text: "Christopher Nolan" },
      { text: "Denis Villeneuve" },
      { text: "Martin Scorsese" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    followUpText: "Christopher Nolan had been nominated 5 times before finally winning for Oppenheimer in 2024!",
    timeLimit: 15,
  },
  {
    text: "What animated film features a clownfish searching for his son?",
    options: [
      { text: "Shark Tale" },
      { text: "Finding Nemo" },
      { text: "The Little Mermaid" },
      { text: "Moana" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "Which movie features the quote 'Here's looking at you, kid'?",
    options: [
      { text: "Gone with the Wind" },
      { text: "Casablanca" },
      { text: "Citizen Kane" },
      { text: "The Maltese Falcon" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 18,
  },
  {
    text: "What is the name of the fictional African country in Black Panther?",
    options: [
      { text: "Zamunda" },
      { text: "Wakanda" },
      { text: "Genovia" },
      { text: "Latveria" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "Which TV series is set in the fictional continents of Westeros and Essos?",
    options: [
      { text: "The Witcher" },
      { text: "Game of Thrones" },
      { text: "Lord of the Rings" },
      { text: "Wheel of Time" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "Who directed the movie 'Jaws'?",
    options: [
      { text: "George Lucas" },
      { text: "Steven Spielberg" },
      { text: "Francis Ford Coppola" },
      { text: "Martin Scorsese" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "What year was the first Harry Potter movie released?",
    options: [
      { text: "1999" },
      { text: "2000" },
      { text: "2001" },
      { text: "2002" },
    ],
    correctOptionIndex: 2,
    category: "movies_tv",
    timeLimit: 18,
  },
  {
    text: "Which actor played Iron Man in the Marvel Cinematic Universe?",
    options: [
      { text: "Chris Evans" },
      { text: "Robert Downey Jr." },
      { text: "Chris Hemsworth" },
      { text: "Mark Ruffalo" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "What is the longest-running animated TV show in the US?",
    options: [
      { text: "South Park" },
      { text: "Family Guy" },
      { text: "The Simpsons" },
      { text: "SpongeBob SquarePants" },
    ],
    correctOptionIndex: 2,
    category: "movies_tv",
    followUpText: "The Simpsons first aired in 1989 and is still going strong!",
    timeLimit: 15,
  },
  {
    text: "Which film won the first Academy Award for Best Picture?",
    options: [
      { text: "Sunrise" },
      { text: "Wings" },
      { text: "The Jazz Singer" },
      { text: "All Quiet on the Western Front" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    followUpText: "Wings won the first Best Picture Oscar at the 1929 Academy Awards!",
    timeLimit: 20,
  },
  {
    text: "What is the name of the hobbit played by Elijah Wood?",
    options: [
      { text: "Sam" },
      { text: "Pippin" },
      { text: "Frodo" },
      { text: "Merry" },
    ],
    correctOptionIndex: 2,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "Which streaming service created 'Squid Game'?",
    options: [
      { text: "Amazon Prime" },
      { text: "Netflix" },
      { text: "Disney+" },
      { text: "HBO Max" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },
  {
    text: "What phrase is associated with the 'Mandalorian' character Baby Yoda?",
    options: [
      { text: "May the Force be with you" },
      { text: "This is the way" },
      { text: "I have spoken" },
      { text: "Grogu hungry" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 18,
  },
  {
    text: "Who voices Woody in the Toy Story movies?",
    options: [
      { text: "Tim Allen" },
      { text: "Tom Hanks" },
      { text: "Billy Crystal" },
      { text: "Robin Williams" },
    ],
    correctOptionIndex: 1,
    category: "movies_tv",
    timeLimit: 15,
  },

  // ============================================
  // FOOD & DRINK (17 questions)
  // ============================================
  {
    text: "Which country has the most Michelin-starred restaurants?",
    options: [
      { text: "France" },
      { text: "Italy" },
      { text: "Japan" },
      { text: "Germany" },
    ],
    correctOptionIndex: 0,
    category: "food_drink",
    timeLimit: 17,
  },
  {
    text: "What is the main ingredient in traditional hummus?",
    options: [
      { text: "Lentils" },
      { text: "Black beans" },
      { text: "Chickpeas" },
      { text: "White beans" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "Which fruit is known as the 'king of fruits' in Southeast Asia?",
    options: [
      { text: "Mango" },
      { text: "Durian" },
      { text: "Jackfruit" },
      { text: "Papaya" },
    ],
    correctOptionIndex: 1,
    category: "food_drink",
    followUpText: "Durian is famous for its strong smell - it's banned in many hotels and public transport!",
    timeLimit: 17,
  },
  {
    text: "What type of pasta is shaped like little ears?",
    options: [
      { text: "Farfalle" },
      { text: "Orecchiette" },
      { text: "Conchiglie" },
      { text: "Rotini" },
    ],
    correctOptionIndex: 1,
    category: "food_drink",
    followUpText: "Orecchiette means 'little ears' in Italian!",
    timeLimit: 18,
  },
  {
    text: "Which spice is the most expensive by weight?",
    options: [
      { text: "Vanilla" },
      { text: "Cardamom" },
      { text: "Saffron" },
      { text: "Cinnamon" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    timeLimit: 16,
  },
  {
    text: "What is the most popular pizza topping in the United States?",
    options: [
      { text: "Mushrooms" },
      { text: "Pepperoni" },
      { text: "Sausage" },
      { text: "Extra cheese" },
    ],
    correctOptionIndex: 1,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "From which country does feta cheese originate?",
    options: [
      { text: "Italy" },
      { text: "France" },
      { text: "Greece" },
      { text: "Turkey" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "What is the main spirit in a Margarita?",
    options: [
      { text: "Rum" },
      { text: "Vodka" },
      { text: "Tequila" },
      { text: "Gin" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "Which country is the largest producer of coffee?",
    options: [
      { text: "Colombia" },
      { text: "Vietnam" },
      { text: "Brazil" },
      { text: "Ethiopia" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    followUpText: "Brazil produces about one-third of all the world's coffee!",
    timeLimit: 18,
  },
  {
    text: "What type of food is a 'brioche'?",
    options: [
      { text: "Pasta" },
      { text: "Bread" },
      { text: "Cheese" },
      { text: "Pastry" },
    ],
    correctOptionIndex: 1,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "Which nut is used to make marzipan?",
    options: [
      { text: "Walnut" },
      { text: "Pistachio" },
      { text: "Almond" },
      { text: "Hazelnut" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "What is the national dish of Japan?",
    options: [
      { text: "Sushi" },
      { text: "Ramen" },
      { text: "Curry rice" },
      { text: "Tempura" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    followUpText: "While sushi is more famous abroad, curry rice is actually the national dish of Japan!",
    timeLimit: 18,
  },
  {
    text: "What is the main ingredient in guacamole?",
    options: [
      { text: "Tomato" },
      { text: "Avocado" },
      { text: "Lime" },
      { text: "Cilantro" },
    ],
    correctOptionIndex: 1,
    category: "food_drink",
    timeLimit: 12,
  },
  {
    text: "Which cheese has holes in it?",
    options: [
      { text: "Cheddar" },
      { text: "Swiss" },
      { text: "Brie" },
      { text: "Gouda" },
    ],
    correctOptionIndex: 1,
    category: "food_drink",
    followUpText: "The holes in Swiss cheese are caused by bacteria releasing carbon dioxide during fermentation!",
    timeLimit: 15,
  },
  {
    text: "What is sake made from?",
    options: [
      { text: "Wheat" },
      { text: "Barley" },
      { text: "Rice" },
      { text: "Potatoes" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "Which fruit is used to make prunes?",
    options: [
      { text: "Apricots" },
      { text: "Plums" },
      { text: "Dates" },
      { text: "Figs" },
    ],
    correctOptionIndex: 1,
    category: "food_drink",
    timeLimit: 15,
  },
  {
    text: "What gives bread its spongy texture?",
    options: [
      { text: "Baking soda" },
      { text: "Eggs" },
      { text: "Yeast" },
      { text: "Sugar" },
    ],
    correctOptionIndex: 2,
    category: "food_drink",
    timeLimit: 15,
  },

  // ============================================
  // PROGRAMMING & DEV (20 questions)
  // ============================================
  {
    text: "What does 'HTTP' stand for?",
    options: [
      { text: "HyperText Transfer Protocol" },
      { text: "High Tech Transfer Program" },
      { text: "Home Tool Transfer Protocol" },
      { text: "Hyperlink Text Transfer Protocol" },
    ],
    correctOptionIndex: 0,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "Which programming language is known for its coffee cup logo?",
    options: [
      { text: "Python" },
      { text: "JavaScript" },
      { text: "Java" },
      { text: "C++" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    followUpText: "Java was named after Java coffee, which is why it has a coffee cup logo!",
    timeLimit: 15,
  },
  {
    text: "What does 'CPU' stand for?",
    options: [
      { text: "Central Processing Unit" },
      { text: "Computer Personal Unit" },
      { text: "Central Program Utility" },
      { text: "Core Processing Unit" },
    ],
    correctOptionIndex: 0,
    category: "programming",
    timeLimit: 15,
  },
  {
    text: "Which company created the Python programming language?",
    options: [
      { text: "Microsoft" },
      { text: "Google" },
      { text: "It was created by an individual" },
      { text: "Apple" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    followUpText: "Python was created by Guido van Rossum in 1991, named after Monty Python!",
    timeLimit: 18,
  },
  {
    text: "What is the most popular version control system?",
    options: [
      { text: "SVN" },
      { text: "Mercurial" },
      { text: "Git" },
      { text: "CVS" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    timeLimit: 15,
  },
  {
    text: "What does 'API' stand for?",
    options: [
      { text: "Application Programming Interface" },
      { text: "Automated Program Integration" },
      { text: "Application Process Integration" },
      { text: "Automated Programming Interface" },
    ],
    correctOptionIndex: 0,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "Which company owns GitHub?",
    options: [
      { text: "Google" },
      { text: "Amazon" },
      { text: "Microsoft" },
      { text: "Meta" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    followUpText: "Microsoft acquired GitHub in 2018 for $7.5 billion!",
    timeLimit: 15,
  },
  {
    text: "What programming language is primarily used for iOS development?",
    options: [
      { text: "Kotlin" },
      { text: "Swift" },
      { text: "Java" },
      { text: "C#" },
    ],
    correctOptionIndex: 1,
    category: "programming",
    timeLimit: 15,
  },
  {
    text: "What does 'SQL' stand for?",
    options: [
      { text: "Simple Query Language" },
      { text: "Structured Query Language" },
      { text: "System Query Logic" },
      { text: "Standard Query Language" },
    ],
    correctOptionIndex: 1,
    category: "programming",
    timeLimit: 15,
  },
  {
    text: "Which company developed the TypeScript language?",
    options: [
      { text: "Google" },
      { text: "Facebook" },
      { text: "Microsoft" },
      { text: "Amazon" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    timeLimit: 15,
  },
  {
    text: "What is the keyboard shortcut for 'Copy' on Windows?",
    options: [
      { text: "Ctrl + V" },
      { text: "Ctrl + C" },
      { text: "Ctrl + X" },
      { text: "Ctrl + Z" },
    ],
    correctOptionIndex: 1,
    category: "programming",
    timeLimit: 12,
  },
  {
    text: "What does 'DNS' stand for?",
    options: [
      { text: "Domain Name System" },
      { text: "Digital Network Service" },
      { text: "Data Name Server" },
      { text: "Dynamic Network System" },
    ],
    correctOptionIndex: 0,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "Which company created React.js?",
    options: [
      { text: "Google" },
      { text: "Facebook (Meta)" },
      { text: "Microsoft" },
      { text: "Twitter" },
    ],
    correctOptionIndex: 1,
    category: "programming",
    timeLimit: 15,
  },
  {
    text: "What is the default port for HTTP?",
    options: [
      { text: "21" },
      { text: "80" },
      { text: "443" },
      { text: "8080" },
    ],
    correctOptionIndex: 1,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "What year was the first iPhone released?",
    options: [
      { text: "2005" },
      { text: "2007" },
      { text: "2009" },
      { text: "2010" },
    ],
    correctOptionIndex: 1,
    category: "programming",
    timeLimit: 15,
  },
  {
    text: "What does 'SaaS' stand for?",
    options: [
      { text: "Software as a Service" },
      { text: "System as a Solution" },
      { text: "Storage as a Service" },
      { text: "Security as a Solution" },
    ],
    correctOptionIndex: 0,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "Which cloud provider has the largest market share?",
    options: [
      { text: "Microsoft Azure" },
      { text: "Google Cloud" },
      { text: "Amazon Web Services" },
      { text: "IBM Cloud" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "What is the primary purpose of Docker?",
    options: [
      { text: "Version control" },
      { text: "Containerization" },
      { text: "Database management" },
      { text: "Code editing" },
    ],
    correctOptionIndex: 1,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "What programming paradigm does React primarily use?",
    options: [
      { text: "Object-oriented" },
      { text: "Procedural" },
      { text: "Functional/Declarative" },
      { text: "Logic" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    timeLimit: 18,
  },
  {
    text: "What is the time complexity of binary search?",
    options: [
      { text: "O(1)" },
      { text: "O(n)" },
      { text: "O(log n)" },
      { text: "O(n^2)" },
    ],
    correctOptionIndex: 2,
    category: "programming",
    timeLimit: 18,
  },

  // ============================================
  // TECHNOLOGY & GADGETS (18 questions)
  // ============================================
  {
    text: "Which company created the iPhone?",
    options: [
      { text: "Apple" },
      { text: "Samsung" },
      { text: "Google" },
      { text: "Microsoft" },
    ],
    correctOptionIndex: 0,
    category: "technology",
    followUpText: "The first iPhone was unveiled by Steve Jobs on January 9, 2007.",
    timeLimit: 12,
  },
  {
    text: "What does 'Wi-Fi' stand for?",
    options: [
      { text: "Wireless Fidelity" },
      { text: "Nothing - it's a brand name" },
      { text: "Wide Frequency" },
      { text: "Wireless Finder" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    followUpText: "Contrary to popular belief, Wi-Fi doesn't stand for anything. It was coined as a play on 'Hi-Fi' (High Fidelity).",
    timeLimit: 18,
  },
  {
    text: "Which company owns Instagram?",
    options: [
      { text: "Google" },
      { text: "Meta (Facebook)" },
      { text: "Twitter" },
      { text: "Snapchat" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    timeLimit: 15,
  },
  {
    text: "What was the first commercially successful video game console?",
    options: [
      { text: "Atari 2600" },
      { text: "Nintendo NES" },
      { text: "Magnavox Odyssey" },
      { text: "Sega Genesis" },
    ],
    correctOptionIndex: 2,
    category: "technology",
    followUpText: "The Magnavox Odyssey was released in 1972, predating Atari's Pong by several months.",
    timeLimit: 20,
  },
  {
    text: "What does 'GPS' stand for?",
    options: [
      { text: "Global Positioning System" },
      { text: "General Positioning Service" },
      { text: "Geographic Positioning System" },
      { text: "Global Program System" },
    ],
    correctOptionIndex: 0,
    category: "technology",
    timeLimit: 15,
  },
  {
    text: "Which streaming service launched first?",
    options: [
      { text: "Hulu" },
      { text: "Netflix streaming" },
      { text: "Amazon Prime Video" },
      { text: "Disney+" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    followUpText: "Netflix launched streaming in 2007, though it started as a DVD-by-mail service in 1997.",
    timeLimit: 18,
  },
  {
    text: "What year was the first text message (SMS) sent?",
    options: [
      { text: "1985" },
      { text: "1992" },
      { text: "1998" },
      { text: "2001" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    followUpText: "The first SMS was 'Merry Christmas' sent on December 3, 1992.",
    timeLimit: 20,
  },
  {
    text: "What does 'USB' stand for?",
    options: [
      { text: "Universal Serial Bus" },
      { text: "United System Bridge" },
      { text: "Universal System Backup" },
      { text: "Unified Serial Bridge" },
    ],
    correctOptionIndex: 0,
    category: "technology",
    timeLimit: 15,
  },
  {
    text: "Which company developed the Android operating system?",
    options: [
      { text: "Apple" },
      { text: "Google" },
      { text: "Samsung" },
      { text: "Microsoft" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    followUpText: "Android was originally developed by Android Inc., which Google acquired in 2005.",
    timeLimit: 15,
  },
  {
    text: "What was the first search engine on the internet?",
    options: [
      { text: "Google" },
      { text: "Yahoo" },
      { text: "Archie" },
      { text: "AltaVista" },
    ],
    correctOptionIndex: 2,
    category: "technology",
    followUpText: "Archie was created in 1990, predating the World Wide Web. Google didn't launch until 1998.",
    timeLimit: 20,
  },
  {
    text: "Which social media platform has the most monthly active users?",
    options: [
      { text: "Instagram" },
      { text: "TikTok" },
      { text: "Facebook" },
      { text: "YouTube" },
    ],
    correctOptionIndex: 2,
    category: "technology",
    timeLimit: 15,
  },
  {
    text: "What does 'LED' stand for?",
    options: [
      { text: "Light Emitting Diode" },
      { text: "Laser Emitting Device" },
      { text: "Light Energy Display" },
      { text: "Low Energy Diode" },
    ],
    correctOptionIndex: 0,
    category: "technology",
    timeLimit: 15,
  },
  {
    text: "Which company created the first computer mouse?",
    options: [
      { text: "Apple" },
      { text: "IBM" },
      { text: "Xerox" },
      { text: "Microsoft" },
    ],
    correctOptionIndex: 2,
    category: "technology",
    followUpText: "Douglas Engelbart invented the mouse at Stanford Research Institute, but Xerox PARC developed the first commercial version.",
    timeLimit: 20,
  },
  {
    text: "What year was YouTube founded?",
    options: [
      { text: "2003" },
      { text: "2005" },
      { text: "2007" },
      { text: "2009" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    followUpText: "YouTube was founded in February 2005 and acquired by Google in 2006 for $1.65 billion.",
    timeLimit: 18,
  },
  {
    text: "What does 'HDMI' stand for?",
    options: [
      { text: "High Definition Media Interface" },
      { text: "High-Definition Multimedia Interface" },
      { text: "High Digital Media Input" },
      { text: "Home Digital Multimedia Interface" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    timeLimit: 18,
  },
  {
    text: "Which company makes the PlayStation gaming console?",
    options: [
      { text: "Nintendo" },
      { text: "Microsoft" },
      { text: "Sony" },
      { text: "Sega" },
    ],
    correctOptionIndex: 2,
    category: "technology",
    timeLimit: 12,
  },
  {
    text: "What was the name of the first iPhone model with Face ID?",
    options: [
      { text: "iPhone 8" },
      { text: "iPhone X" },
      { text: "iPhone 11" },
      { text: "iPhone XS" },
    ],
    correctOptionIndex: 1,
    category: "technology",
    followUpText: "iPhone X (pronounced 'ten') was released in 2017 for Apple's 10th anniversary.",
    timeLimit: 18,
  },
  {
    text: "What is the most popular web browser as of 2024?",
    options: [
      { text: "Safari" },
      { text: "Firefox" },
      { text: "Chrome" },
      { text: "Edge" },
    ],
    correctOptionIndex: 2,
    category: "technology",
    followUpText: "Chrome has over 60% market share globally.",
    timeLimit: 15,
  },

  // ============================================
  // ANIMALS (17 questions)
  // ============================================
  {
    text: "What do you call a group of flamingos?",
    options: [
      { text: "A flock" },
      { text: "A colony" },
      { text: "A flamboyance" },
      { text: "A squadron" },
    ],
    correctOptionIndex: 2,
    category: "animals",
    followUpText: "A 'flamboyance' is the perfect name for these pink show-offs!",
    timeLimit: 18,
  },
  {
    text: "What is the only mammal capable of true flight?",
    options: [
      { text: "Flying squirrel" },
      { text: "Bat" },
      { text: "Flying fish" },
      { text: "Sugar glider" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    followUpText: "Flying squirrels and sugar gliders glide, but bats actually fly!",
    timeLimit: 16,
  },
  {
    text: "Which animal has the longest lifespan?",
    options: [
      { text: "Elephant" },
      { text: "Galapagos tortoise" },
      { text: "Greenland shark" },
      { text: "Blue whale" },
    ],
    correctOptionIndex: 2,
    category: "animals",
    followUpText: "Greenland sharks can live over 400 years, making them the longest-living vertebrates!",
    timeLimit: 18,
  },
  {
    text: "What should you do if you encounter a bear in the wild?",
    options: [
      { text: "Run away as fast as possible" },
      { text: "Make yourself look big and back away slowly" },
      { text: "Play dead immediately" },
      { text: "Try to climb the nearest tree" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    timeLimit: 20,
  },
  {
    text: "How many hearts does an octopus have?",
    options: [
      { text: "1" },
      { text: "2" },
      { text: "3" },
      { text: "4" },
    ],
    correctOptionIndex: 2,
    category: "animals",
    followUpText: "Octopuses have 3 hearts - two pump blood to the gills, one pumps it to the body!",
    timeLimit: 15,
  },
  {
    text: "What is a baby kangaroo called?",
    options: [
      { text: "Calf" },
      { text: "Joey" },
      { text: "Pup" },
      { text: "Kit" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    timeLimit: 12,
  },
  {
    text: "Which animal is known for sleeping standing up?",
    options: [
      { text: "Cow" },
      { text: "Horse" },
      { text: "Giraffe" },
      { text: "All of the above" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    followUpText: "Horses can sleep standing up thanks to a 'stay apparatus' in their legs!",
    timeLimit: 18,
  },
  {
    text: "What is the largest species of shark?",
    options: [
      { text: "Great White Shark" },
      { text: "Tiger Shark" },
      { text: "Whale Shark" },
      { text: "Hammerhead Shark" },
    ],
    correctOptionIndex: 2,
    category: "animals",
    followUpText: "Whale sharks can grow up to 40 feet long but they're gentle filter feeders!",
    timeLimit: 15,
  },
  {
    text: "Which bird can fly backwards?",
    options: [
      { text: "Owl" },
      { text: "Hummingbird" },
      { text: "Eagle" },
      { text: "Penguin" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    timeLimit: 15,
  },
  {
    text: "What is the fastest land animal?",
    options: [
      { text: "Lion" },
      { text: "Cheetah" },
      { text: "Antelope" },
      { text: "Greyhound" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    followUpText: "Cheetahs can reach speeds up to 70 mph in short bursts!",
    timeLimit: 15,
  },
  {
    text: "Which animal has the most legs?",
    options: [
      { text: "Centipede" },
      { text: "Millipede" },
      { text: "Spider" },
      { text: "Caterpillar" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    followUpText: "Millipedes can have over 750 legs, while centipedes typically have 30-354!",
    timeLimit: 18,
  },
  {
    text: "What is a group of wolves called?",
    options: [
      { text: "Herd" },
      { text: "Pack" },
      { text: "Flock" },
      { text: "Pride" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    timeLimit: 12,
  },
  {
    text: "Which animal's fingerprints are nearly identical to human fingerprints?",
    options: [
      { text: "Gorilla" },
      { text: "Chimpanzee" },
      { text: "Koala" },
      { text: "Orangutan" },
    ],
    correctOptionIndex: 2,
    category: "animals",
    followUpText: "Koala fingerprints are so similar to humans they've confused crime scene investigators!",
    timeLimit: 20,
  },
  {
    text: "What is the only continent where giraffes live in the wild?",
    options: [
      { text: "Asia" },
      { text: "Africa" },
      { text: "Australia" },
      { text: "South America" },
    ],
    correctOptionIndex: 1,
    category: "animals",
    timeLimit: 15,
  },
  {
    text: "How long can a snail sleep?",
    options: [
      { text: "8 hours" },
      { text: "1 week" },
      { text: "1 month" },
      { text: "3 years" },
    ],
    correctOptionIndex: 3,
    category: "animals",
    followUpText: "Snails can sleep for up to 3 years if weather conditions are not ideal!",
    timeLimit: 18,
  },
  {
    text: "Which insect can lift 50 times its own body weight?",
    options: [
      { text: "Ant" },
      { text: "Bee" },
      { text: "Beetle" },
      { text: "Grasshopper" },
    ],
    correctOptionIndex: 0,
    category: "animals",
    timeLimit: 15,
  },
  {
    text: "What animal is the symbol of the World Wildlife Fund (WWF)?",
    options: [
      { text: "Tiger" },
      { text: "Elephant" },
      { text: "Giant Panda" },
      { text: "Polar Bear" },
    ],
    correctOptionIndex: 2,
    category: "animals",
    timeLimit: 15,
  },

  // ============================================
  // LITERATURE (17 questions)
  // ============================================
  {
    text: "Who wrote 'Romeo and Juliet'?",
    options: [
      { text: "Charles Dickens" },
      { text: "William Shakespeare" },
      { text: "Jane Austen" },
      { text: "Oscar Wilde" },
    ],
    correctOptionIndex: 1,
    category: "literature",
    timeLimit: 12,
  },
  {
    text: "What is the best-selling book of all time?",
    options: [
      { text: "Harry Potter and the Philosopher's Stone" },
      { text: "The Lord of the Rings" },
      { text: "Don Quixote" },
      { text: "The Bible" },
    ],
    correctOptionIndex: 3,
    category: "literature",
    followUpText: "The Bible has sold an estimated 5 billion copies!",
    timeLimit: 18,
  },
  {
    text: "Who wrote '1984'?",
    options: [
      { text: "Aldous Huxley" },
      { text: "George Orwell" },
      { text: "Ray Bradbury" },
      { text: "H.G. Wells" },
    ],
    correctOptionIndex: 1,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "What is the name of Harry Potter's owl?",
    options: [
      { text: "Errol" },
      { text: "Hedwig" },
      { text: "Pigwidgeon" },
      { text: "Scabbers" },
    ],
    correctOptionIndex: 1,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "Who is the author of 'The Great Gatsby'?",
    options: [
      { text: "Ernest Hemingway" },
      { text: "F. Scott Fitzgerald" },
      { text: "John Steinbeck" },
      { text: "Mark Twain" },
    ],
    correctOptionIndex: 1,
    category: "literature",
    timeLimit: 18,
  },
  {
    text: "In which book series would you find the character Katniss Everdeen?",
    options: [
      { text: "Divergent" },
      { text: "The Hunger Games" },
      { text: "Twilight" },
      { text: "The Maze Runner" },
    ],
    correctOptionIndex: 1,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "Who wrote 'Pride and Prejudice'?",
    options: [
      { text: "Charlotte Bronte" },
      { text: "Emily Bronte" },
      { text: "Jane Austen" },
      { text: "Virginia Woolf" },
    ],
    correctOptionIndex: 2,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "What is the first book in 'The Chronicles of Narnia' series?",
    options: [
      { text: "The Lion, the Witch and the Wardrobe" },
      { text: "The Magician's Nephew" },
      { text: "Prince Caspian" },
      { text: "The Horse and His Boy" },
    ],
    correctOptionIndex: 0,
    category: "literature",
    followUpText: "Though 'The Magician's Nephew' is chronologically first, 'The Lion, the Witch and the Wardrobe' was published first!",
    timeLimit: 20,
  },
  {
    text: "Who wrote 'The Catcher in the Rye'?",
    options: [
      { text: "Jack Kerouac" },
      { text: "J.D. Salinger" },
      { text: "William Golding" },
      { text: "Kurt Vonnegut" },
    ],
    correctOptionIndex: 1,
    category: "literature",
    timeLimit: 18,
  },
  {
    text: "What is Sherlock Holmes's address?",
    options: [
      { text: "221B Baker Street" },
      { text: "10 Downing Street" },
      { text: "4 Privet Drive" },
      { text: "1600 Pennsylvania Avenue" },
    ],
    correctOptionIndex: 0,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "Who wrote 'The Lord of the Rings'?",
    options: [
      { text: "C.S. Lewis" },
      { text: "J.R.R. Tolkien" },
      { text: "George R.R. Martin" },
      { text: "Terry Pratchett" },
    ],
    correctOptionIndex: 1,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "What was Dr. Seuss's real name?",
    options: [
      { text: "Theodore Seuss" },
      { text: "Samuel Seuss" },
      { text: "Theodor Seuss Geisel" },
      { text: "Steven Seuss" },
    ],
    correctOptionIndex: 2,
    category: "literature",
    timeLimit: 18,
  },
  {
    text: "Which author created the character of James Bond?",
    options: [
      { text: "John le Carre" },
      { text: "Tom Clancy" },
      { text: "Ian Fleming" },
      { text: "Robert Ludlum" },
    ],
    correctOptionIndex: 2,
    category: "literature",
    timeLimit: 18,
  },
  {
    text: "What is the name of the whale in 'Moby-Dick'?",
    options: [
      { text: "Ahab" },
      { text: "Ishmael" },
      { text: "Moby Dick" },
      { text: "Queequeg" },
    ],
    correctOptionIndex: 2,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "Who wrote 'To Kill a Mockingbird'?",
    options: [
      { text: "Harper Lee" },
      { text: "Truman Capote" },
      { text: "Flannery O'Connor" },
      { text: "Tennessee Williams" },
    ],
    correctOptionIndex: 0,
    category: "literature",
    timeLimit: 15,
  },
  {
    text: "What is the name of the fictional wizarding school in Harry Potter?",
    options: [
      { text: "Durmstrang" },
      { text: "Beauxbatons" },
      { text: "Hogwarts" },
      { text: "Ilvermorny" },
    ],
    correctOptionIndex: 2,
    category: "literature",
    timeLimit: 12,
  },
  {
    text: "Who wrote 'Frankenstein'?",
    options: [
      { text: "Bram Stoker" },
      { text: "Edgar Allan Poe" },
      { text: "Mary Shelley" },
      { text: "H.P. Lovecraft" },
    ],
    correctOptionIndex: 2,
    category: "literature",
    followUpText: "Mary Shelley wrote Frankenstein when she was only 18 years old!",
    timeLimit: 18,
  },

  // ============================================
  // GENERAL KNOWLEDGE (18 questions)
  // ============================================
  {
    text: "How many colors are in a rainbow?",
    options: [
      { text: "5" },
      { text: "6" },
      { text: "7" },
      { text: "8" },
    ],
    correctOptionIndex: 2,
    category: "general",
    followUpText: "Red, Orange, Yellow, Green, Blue, Indigo, Violet - Roy G. Biv!",
    timeLimit: 12,
  },
  {
    text: "What is the only letter that doesn't appear in any U.S. state name?",
    options: [
      { text: "Q" },
      { text: "X" },
      { text: "Z" },
      { text: "J" },
    ],
    correctOptionIndex: 0,
    category: "general",
    timeLimit: 18,
  },
  {
    text: "What is the dot over the letters 'i' and 'j' called?",
    options: [
      { text: "Diacritic" },
      { text: "Tittle" },
      { text: "Serif" },
      { text: "Apex" },
    ],
    correctOptionIndex: 1,
    category: "general",
    timeLimit: 18,
  },
  {
    text: "What is the fear of long words called?",
    options: [
      { text: "Logophobia" },
      { text: "Hippopotomonstrosesquippedaliophobia" },
      { text: "Sesquipedalophobia" },
      { text: "Verbophobia" },
    ],
    correctOptionIndex: 1,
    category: "general",
    followUpText: "Yes, someone really named the fear of long words with a 36-letter word. That's a cruel joke!",
    timeLimit: 20,
  },
  {
    text: "According to surveys, what do most people prefer: cats or dogs?",
    options: [
      { text: "Cats" },
      { text: "Dogs" },
      { text: "Equal preference" },
      { text: "Neither" },
    ],
    correctOptionIndex: 1,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "What is the most common favorite color worldwide?",
    options: [
      { text: "Red" },
      { text: "Green" },
      { text: "Blue" },
      { text: "Purple" },
    ],
    correctOptionIndex: 2,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "Which day of the week do most people consider their favorite?",
    options: [
      { text: "Friday" },
      { text: "Saturday" },
      { text: "Sunday" },
      { text: "Monday" },
    ],
    correctOptionIndex: 1,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "Which company makes the PlayStation?",
    options: [
      { text: "Microsoft" },
      { text: "Nintendo" },
      { text: "Sony" },
      { text: "Sega" },
    ],
    correctOptionIndex: 2,
    category: "general",
    timeLimit: 12,
  },
  {
    text: "What is the currency of Japan?",
    options: [
      { text: "Won" },
      { text: "Yuan" },
      { text: "Yen" },
      { text: "Ringgit" },
    ],
    correctOptionIndex: 2,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "How many sides does a hexagon have?",
    options: [
      { text: "5" },
      { text: "6" },
      { text: "7" },
      { text: "8" },
    ],
    correctOptionIndex: 1,
    category: "general",
    timeLimit: 12,
  },
  {
    text: "What is the largest ocean on Earth?",
    options: [
      { text: "Atlantic Ocean" },
      { text: "Indian Ocean" },
      { text: "Pacific Ocean" },
      { text: "Arctic Ocean" },
    ],
    correctOptionIndex: 2,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "What is the national language of Brazil?",
    options: [
      { text: "Spanish" },
      { text: "Portuguese" },
      { text: "French" },
      { text: "Brazilian" },
    ],
    correctOptionIndex: 1,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "How many continents are there?",
    options: [
      { text: "5" },
      { text: "6" },
      { text: "7" },
      { text: "8" },
    ],
    correctOptionIndex: 2,
    category: "general",
    timeLimit: 12,
  },
  {
    text: "What year did the Titanic sink?",
    options: [
      { text: "1905" },
      { text: "1912" },
      { text: "1918" },
      { text: "1923" },
    ],
    correctOptionIndex: 1,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "What is the tallest building in the world as of 2024?",
    options: [
      { text: "Shanghai Tower" },
      { text: "One World Trade Center" },
      { text: "Burj Khalifa" },
      { text: "Taipei 101" },
    ],
    correctOptionIndex: 2,
    category: "general",
    followUpText: "The Burj Khalifa in Dubai stands at 828 meters (2,717 feet)!",
    timeLimit: 18,
  },
  {
    text: "What is the smallest prime number?",
    options: [
      { text: "0" },
      { text: "1" },
      { text: "2" },
      { text: "3" },
    ],
    correctOptionIndex: 2,
    category: "general",
    followUpText: "1 is not considered a prime number - 2 is the smallest and only even prime!",
    timeLimit: 15,
  },
  {
    text: "What does the 'E' stand for in E=mc^2?",
    options: [
      { text: "Electricity" },
      { text: "Energy" },
      { text: "Element" },
      { text: "Entropy" },
    ],
    correctOptionIndex: 1,
    category: "general",
    timeLimit: 15,
  },
  {
    text: "What is the currency used in the United Kingdom?",
    options: [
      { text: "Euro" },
      { text: "Dollar" },
      { text: "Pound Sterling" },
      { text: "Franc" },
    ],
    correctOptionIndex: 2,
    category: "general",
    timeLimit: 15,
  },
];
